language: rust
rust:
  - nightly
sudo: false
cache: apt

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - gfortran
    - liblapack-dev
    - libblas-dev
    - libblas3gf
    - libopenblas-dev
    - binutils-dev
    - libgsl0-dev
    - libgsl0ldbl
    - gsl-bin

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
    
script:
  - travis-cargo build && travis-cargo test

after_success:
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
