language: rust
rust:
  - nightly
sudo: false
cache: apt

addons:
  apt:
    packages:
    - libelf-dev
    - libdw-dev
    - gfortran
    - liblapack-dev
    - libblas-dev
    - libblas3gf
    - libopenblas-dev
